name: Node Publisher

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run build
    - name: version & publish
      uses: geeman201/conventional-changelog-npm-publish/@v14
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      
